ExternalProject_Add(z3
    GIT_REPOSITORY
        "https://github.com/Z3Prover/z3"
    GIT_TAG
        "z3-4.11.2"
    GIT_PROGRESS
        ON
    GIT_SHALLOW
        ON
    CMAKE_CACHE_ARGS
        ${CMAKE_ARGS}
        "-DZ3_BUILD_LIBZ3_SHARED:STRING=OFF"
    CMAKE_GENERATOR
        "Ninja"
)